// Re-export from constants for clarity
const {
  ROLES,
  ROLE_HIERARCHY,
  PERMISSIONS,
  ORDER_STATUS,
  PAYMENT_METHODS,
  PAYMENT_STATUS,
  STOCK_STATUS,
  PRODUCT_STATUS,
  APPROVAL_STATUS,
  WEBSITE_STATUS,
  REVIEW_STATUS,
  COUPON_STATUS,
  COUPON_TYPES,
  OFFER_TYPES,
  NAVIGATION_TYPES,
  HOMEPAGE_SECTION_TYPES,
  INVENTORY_TX_TYPES,
  RTO_STATUS,
  SORT_OPTIONS,
  GST_RATE,
} = require('../constants');

module.exports = {
  Roles: ROLES,
  RoleHierarchy: ROLE_HIERARCHY,
  Permissions: PERMISSIONS,
  OrderStatus: ORDER_STATUS,
  PaymentMethods: PAYMENT_METHODS,
  PaymentStatus: PAYMENT_STATUS,
  StockStatus: STOCK_STATUS,
  ProductStatus: PRODUCT_STATUS,
  ApprovalStatus: APPROVAL_STATUS,
  WebsiteStatus: WEBSITE_STATUS,
  ReviewStatus: REVIEW_STATUS,
  CouponStatus: COUPON_STATUS,
  CouponTypes: COUPON_TYPES,
  OfferTypes: OFFER_TYPES,
  NavigationTypes: NAVIGATION_TYPES,
  HomepageSectionTypes: HOMEPAGE_SECTION_TYPES,
  InventoryTxTypes: INVENTORY_TX_TYPES,
  RTOStatus: RTO_STATUS,
  SortOptions: SORT_OPTIONS,
  GSTRate: GST_RATE,
};

